name: super-linter

on: push

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run super linter
        uses: github/super-linter/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: $4{{ secrets.GITHUB_TOKEN }}
